apiVersion: apps/v1
kind: Deployment
metadata:
    name: iis-demo
    labels:
      app: iis-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iis-demo
  template:
    metadata:
      labels:
        app: iis-demo
    spec:
      tolerations:
        - key: kubernetes.io/os
          operator: Equal
          value: windows
          effect: NoSchedule    
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: iis-demo
        image: mcr.microsoft.com/windows/servercore/iis
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: iis-sample
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: iis-demo